### ISSUE TITLE
Link to video

### ISSUE THREAD

**Issue by Mennaruuk** [mehdihadeli/awesome-dotnet-async#3]
- For the **_C# Channels Explained (System.Threading.Channels)_** video, I got this weird prompt:
![image](https://user-images.githubusercontent.com/52135169/106683426-76575e80-6592-11eb-8628-fe3463afb003.png) 
Luckily, I saw there was a YouTube URL in that URL, so I'd recommend directly linking to the YouTube video: https://youtube.com/watch?v=E0Ld7ZgE4oY

**Comment by mehdihadeli** [comment]
@Mennaruuk Thanks for your report, I will correct these links.

**Comment by mehdihadeli** [comment]
@Mennaruuk Fixed.

**Comment by Mennaruuk** [comment]
Thank you :)
